services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    environment:
      - DD_API_KEY=fcbd7c891d95343fb27e59f537b1761a
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      # - DD_APM_RECEIVER_SOCKET=/var/run/datadog/apm.socket
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      # - DD_DOGSTATSD_SOCKET=/var/run/datadog/dsd.socket
    volumes:
      # - /var/run/datadog:/var/run/datadog  # No necesario para Prometheus scraping
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro  # No existe en macOS/Docker Desktop
      - ./docker/datadog/prometheus:/etc/datadog-agent/conf.d/prometheus.d:ro
    ports: 
      - "8126:8126"   # apm
      - "4317:4317"   # otel
      - "8125:8125/udp"  # dogstatsd
    restart: unless-stopped
